### ISSUE TITLE
Add IPFS Support

### ISSUE THREAD

**Issue by Mistikan** [Thomas-Tsai/partclone#138]
Hello. How do you look at such an idea to add IPSF(https://ipfs.io/) support to your project?
As I see it: not the contents of the file itself are written to the image, but its IPFS parameters (multi-hash) and at the same time, the link to the file — its parameters — is received somewhere.
We transfer this information to an agent who, if this file is not in his database, for example, in an IPFS cluster, then he uploads it there.
When it will be necessary to restore the partition, we will additionally indicate the address of the IPFS cluster, from which we will receive the required files by multi-hash.
How do you like this idea?
Unfortunately, I am not a very good programmer and I did not find a function that exactly reads / copies the file.

**Comment by tjjh89017** [comment]
First, let me describe the usage about Partclone with torrent support
Partclone is a part of CloneZilla project.
CloneZilla could backup/restore your computer.
And CloneZilla Lite Server (or Server Edition) could duplicate the template computer to all others computers 
(for example: I can use CloneZilla to duplicate the template PC to all others in PC room, make all PCs with same OS and data)
And we implement "Bittorrent-based" data transfer method to distribute data.
So Partclone will save the image of disk in EZIO-compatible format. https://github.com/tjjh89017/ezio
And EZIO will take care about restoring disk from image.
This is the purpose of "partclone torrent support".

I hope you can describe some scenario you met.
So I can get some image for this topic.

In the issue that you opened, Did you mean 
"when using Partclone to clone a filesystem or disk, it will store in IPFS, and we just need to send the hash to client who want to restore filesystem. And those client will get the data from IPFS"

I didn't know well about IPFS.
So if anything incorrect, please tell me.
In my understand, IPFS is a blockchain-based internet file storage project.
Because of blockchain, not all nodes will receive all data and store them. 
(Most of nodes will store partial data)

So based on my understand of your idea.
There is some concern:

- IPFS is a public service.
    - Some users won't like to upload data to public. It will cause some security issue.
    - And if your data are stored in the "cloud", when you need to pull those back to local, all clients will consume bandwidth to internet, uplink to internet will be the bottleneck and slow down the progress.
    - Most users use CloneZilla in local network.
- If we can build a IPFS service in local and disconnect from Internet.
    - You need to implement an executable program to send/receive data from the disk and send/receive from IPFS. In other word, you need to convert IPFS "file" from/to disk "block" (Remember that Partclone is a program to backup/restore your disk)
    - IPFS is a complex protocol. It will cost more effort to maintain this protocol for disk backup/restore. It might overkill for this purpose.
- Conclusion
    - IPFS might only solve the problem where the data are stored.
        - we left this question to the users before, they need to decide this location on their own
    - If we want to store the data in IPFS, we still need to find a way to download/upload data from/to IPFS, and convert from/to disk.
        - need to implement new method for this, take effort to develop, maintain and debug

I will say this is hard to replace or overtake Bittorrent because of the scenario we usually met.
It will be an interesting idea to implement, but for now it didn't show much benefit than other methods (Multicast, Broadcast, Bittorrent)

So if you can give us more descriptions, it will help us to imagine.
Thanks

**Comment by Mistikan** [comment]
After talking with @tjjh89017 and looking for more suitable software, I came to the conclusion that partclone is not very suitable for my task. Thank you for understanding.
